AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'example.rb'

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/OpenStructUse:
  Enabled: false
